version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - ./public:/app/public
      - ./build:/app/build
      - /app/node_modules
    ports:
      - 5000:5000
    command: yarn run serve
    environment:
      - NODE_ENV=development

  cypress:
    image: cypress
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:5000
    command: yarn run test:integration
    volumes:
      - ./test/e2e:/app/test/e2e
      - ./cypress.json:/app/cypress.json
