version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app/"
      - "/app/node_modules"
    ports:
      - 3000:3000
    command: yarn start
    environment:
      - NODE_ENV=development

  cypress:
    image: cypress
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:3000
    command: yarn run test:integration
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.json:/app/cypress.json
