version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
      - ./Makefile:/app/Makefile
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development

  cypress:
    image: cypress
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://localhost:5000
    command: make integration-test
    volumes:
      - ./Makefile:/app/Makefile
      - ./test/e2e:/app/test/e2e
      - ./cypress.json:/app/cypress.json
