version: 2.1

workflows:
  test_and_deploy:
    jobs:
      - test

jobs:
  test:
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: Build
          command: make build

      - run:
          name: Run formatting tests
          command: make test:format

      - run:
          name: Unit Tests
          command: make test:unit

      - run:
          name: Integration Tests
          command: make test:integration

      - store_test_results:
          path: test_results
