version: 2.1

executors:
  cypress-demo:
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: true

workflows:
  build_and_test:
    jobs:
      - test_integration

jobs:
  test_integration:
    executor: cypress-demo
    steps:
      - checkout
      - run:
          name: Build integration
          command: docker-compose build

      - run:
          name: Build integration
          command: make test-integration

      - run:
          name: Setup database
          command: docker-compose run web rails db:create db:schema:load db:seed

      - run:
          name: Run integration tests
          command: make test-integration

      - store_test_results:
          path: test_results
