version: 2.1

workflows:
  test_and_deploy:
    jobs:
      - test

jobs:
  test:
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: Build
          command: make install

      - run:
          name: Run tests
          command: make integration-test

      - store_test_results:
          path: test_results
